# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [166]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [167]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [168]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5540, 0.0031, 0.6262],
        [0.6706, 0.8673, 0.6470],
        [0.3630, 0.1267, 0.6798],
        [0.5355, 0.9694, 0.1623],
        [0.1680, 0.7354, 0.1394]])


Get its size

In [169]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [170]:
x[1:3] = 2
print(x)

tensor([[0.5540, 0.0031, 0.6262],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.5355, 0.9694, 0.1623],
        [0.1680, 0.7354, 0.1394]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [171]:
x = torch.Tensor(2,17)
print(x.size())


torch.Size([2, 17])


In [172]:
x = torch.FloatTensor(3,1)
x.size()

torch.Size([3, 1])

In [173]:
x = torch.LongTensor(5,2,1)
x.size()


torch.Size([5, 2, 1])

In [174]:
x = torch.full_like(x, 7)
x

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [175]:
x = torch.ByteTensor(5,)
print(x)
x[1:4] = 1
print(x)

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [176]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[1.5613, 0.5001, 0.7837],
        [0.4013, 0.9032, 1.0431],
        [1.4704, 1.4765, 0.7954],
        [0.5222, 1.0805, 0.7390],
        [0.1841, 1.3454, 0.7391]])


### 2.2 Addition: syntax 2

In [177]:
print(torch.add(x, y))

tensor([[1.5613, 0.5001, 0.7837],
        [0.4013, 0.9032, 1.0431],
        [1.4704, 1.4765, 0.7954],
        [0.5222, 1.0805, 0.7390],
        [0.1841, 1.3454, 0.7391]])


### 2.3 Addition: giving an output tensor

In [178]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5613, 0.5001, 0.7837],
        [0.4013, 0.9032, 1.0431],
        [1.4704, 1.4765, 0.7954],
        [0.5222, 1.0805, 0.7390],
        [0.1841, 1.3454, 0.7391]])


### 2.4 Addition: in-place

adds `x` to `y`

In [179]:
y.add_(x)
print(y)

tensor([[1.5613, 0.5001, 0.7837],
        [0.4013, 0.9032, 1.0431],
        [1.4704, 1.4765, 0.7954],
        [0.5222, 1.0805, 0.7390],
        [0.1841, 1.3454, 0.7391]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [180]:
print(x[:, 1])

tensor([0.3256, 0.2213, 0.5431, 0.6996, 0.6321])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [181]:
# 1. multiplication
print(f"{x.mul(y) = }")
print(f"{torch.mul(x,y) = }")
print(f"{x*y = }")


x.mul(y) = tensor([[1.0117, 0.1628, 0.4160],
        [0.0240, 0.1999, 0.1079],
        [1.1912, 0.8019, 0.2918],
        [0.0265, 0.7560, 0.3149],
        [0.0061, 0.8504, 0.2503]])
torch.mul(x,y) = tensor([[1.0117, 0.1628, 0.4160],
        [0.0240, 0.1999, 0.1079],
        [1.1912, 0.8019, 0.2918],
        [0.0265, 0.7560, 0.3149],
        [0.0061, 0.8504, 0.2503]])
x*y = tensor([[1.0117, 0.1628, 0.4160],
        [0.0240, 0.1999, 0.1079],
        [1.1912, 0.8019, 0.2918],
        [0.0265, 0.7560, 0.3149],
        [0.0061, 0.8504, 0.2503]])


In [182]:
# 2. inplace
print(f"Before: {x=}")
x.mul_(y)
print(f"After: {x=}")

Before: x=tensor([[0.6480, 0.3256, 0.5308],
        [0.0599, 0.2213, 0.1035],
        [0.8101, 0.5431, 0.3668],
        [0.0508, 0.6996, 0.4260],
        [0.0334, 0.6321, 0.3386]])
After: x=tensor([[1.0117, 0.1628, 0.4160],
        [0.0240, 0.1999, 0.1079],
        [1.1912, 0.8019, 0.2918],
        [0.0265, 0.7560, 0.3149],
        [0.0061, 0.8504, 0.2503]])


In [190]:
# 3. division
print(f"{x.div(y) = }")
print(f"{torch.div(x,y) = }")
print(f"{x/y = }")


x.div(y) = tensor([[0.6480, 0.3256, 0.5308],
        [0.0599, 0.2213, 0.1035],
        [0.8101, 0.5431, 0.3668],
        [0.0508, 0.6996, 0.4260],
        [0.0334, 0.6321, 0.3386]])
torch.div(x,y) = tensor([[0.6480, 0.3256, 0.5308],
        [0.0599, 0.2213, 0.1035],
        [0.8101, 0.5431, 0.3668],
        [0.0508, 0.6996, 0.4260],
        [0.0334, 0.6321, 0.3386]])
x/y = tensor([[0.6480, 0.3256, 0.5308],
        [0.0599, 0.2213, 0.1035],
        [0.8101, 0.5431, 0.3668],
        [0.0508, 0.6996, 0.4260],
        [0.0334, 0.6321, 0.3386]])


In [199]:
# 4. matmul
x1 = torch.fill(torch.Tensor(2,4), 7)
x2 = torch.fill(torch.Tensor(4,2), 3)

print(f"{x1@x2=}")
print(f"{torch.matmul(x1,x2)=}")
print(f"{x1.matmul(x2)=}")


x1@x2=tensor([[84., 84.],
        [84., 84.]])
torch.matmul(x1,x2)=tensor([[84., 84.],
        [84., 84.]])
x1.matmul(x2)=tensor([[84., 84.],
        [84., 84.]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [200]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [201]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [202]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [203]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [211]:
x = torch.ones(5,3)
x_np = x.numpy()
x_torch = torch.from_numpy(x_np)


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
elif torch.mps.is_available():
    x = x.to("mps")
    y = y.to("mps")
    z = x + y
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
tensor([[1.5613, 0.5001, 0.7837],
        [0.4013, 0.9032, 1.0431],
        [1.4704, 1.4765, 0.7954],
        [0.5222, 1.0805, 0.7390],
        [0.1841, 1.3454, 0.7391]], device='mps:0')
tensor([[2.5613, 1.5001, 1.7837],
        [1.4013, 1.9032, 2.0431],
        [2.4704, 2.4765, 1.7954],
        [1.5222, 2.0805, 1.7390],
        [1.1841, 2.3454, 1.7391]], device='mps:0')
